name: Scrape Forex Factory Calendar

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run scraper and save to file
        # This is line 30, where the error likely is.
        # Note the two spaces of indentation.
        run: python -c "import json; from scraper import fetch_and_parse_calendar; data = fetch_and_parse_calendar(); with open('news.json', 'w') as f: json.dump({'events': data}, f, indent=2)"

      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): Update economic calendar data"
          file_pattern: news.json